### ISSUE TITLE
nextflow run on a single sample with latest version 1.0.1 failed -"multi-dimensional indexing on a pandas Series"

### ISSUE THREAD

**Issue by am8265** [quinlan-lab/STRling-nf#2]
Hello Authors,
 I tried running the nextflow pipleine on a single sample (WGS PCR free and another exome) after building the docker image  
from the latest version **1.0.1**. I ran into the following errors, which seems to be an issue with "multi-dimensional indexing on a pandas Series" not being supported in python3.10. Thus, docker image would need to be modified. 

```
Elapsed time: 0:00:11 Calculating z scores
  Traceback (most recent call last):
    File "/opt/conda/envs/main/bin/strling-outliers.py", line 451, in <module>
      main()
    File "/opt/conda/envs/main/bin/strling-outliers.py", line 332, in main
      z = z_score(sum_str_log_wide, mu_sd_estimates)
    File "/opt/conda/envs/main/bin/strling-outliers.py", line 140, in z_score
      return (x - df['mu'][:,np.newaxis])/df['sd'][:,np.newaxis]
    File "/opt/conda/envs/main/lib/python3.10/site-packages/pandas/core/series.py", line 1033, in __getitem__
      return self._get_with(key)
    File "/opt/conda/envs/main/lib/python3.10/site-packages/pandas/core/series.py", line 1048, in _get_with
      return self._get_values_tuple(key)
    File "/opt/conda/envs/main/lib/python3.10/site-packages/pandas/core/series.py", line 1082, in _get_values_tuple
      disallow_ndim_indexing(result)
    File "/opt/conda/envs/main/lib/python3.10/site-packages/pandas/core/indexers/utils.py", line 343, in disallow_ndim_indexing
      raise ValueError(
  ValueError: Multi-dimensional indexing (e.g. `obj[:, None]`) is no longer supported. Convert to a numpy array before indexing instead.

Work dir:
  /nfs/tx/in/STRling-nf-1.0.1/work/fb/44a007fe504136862345d22bf2e71b

Tip: you can replicate the issue by changing to the process work dir and entering the command `bash .command.run`

 -- Check '.nextflow.log' file for details
```
Please let me know if you guys plan on modifying the docker image.
Thanks!

**Comment by hdashnow** [comment]
Thanks for the bug report. I'll see what I can do.
